Numpy

NumPy is a fundamental library for scientific computation in python. it provides support for array and matrices, along with a collection of mathamatical functions to operate on these data structures. 

In [4]:
import numpy as np

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [5]:
arr1 = np.array([1,2,3,4,5])
arr1.reshape((1,5)) #1 row and 5 column

array([[1, 2, 3, 4, 5]])

In [6]:
# 2D Array

arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [9]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
## identity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
## Attributes of numpy

arr = np.array([[1,2,3],[4,5,6]])

print(arr)
print(arr.shape)
print(arr.ndim) # np of dimension
print(arr.size)
print(arr.dtype) # data type
print(arr.itemsize) # Item size in bytes

[[1 2 3]
 [4 5 6]]
(2, 3)
2
6
int64
8


In [14]:
### Numpy Vectorized operation

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

##Element wise addition
print("Addition:" ,arr1 + arr2)
print("Substraction:" ,arr1 - arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]


In [15]:
## Universal Functions

arr = np.array([1,2,3,4,5,6])

print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [17]:
## Array slicing and indexing

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [18]:
arr[0][0]

np.int64(1)

In [20]:
arr[1:, 2:]

array([[ 7,  8],
       [11, 12]])

In [21]:
arr[0:2, 2:]

array([[3, 4],
       [7, 8]])

In [22]:
## Modify array element
arr[0,0]= 100
arr

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [23]:
arr[1:]=100
arr

array([[100,   2,   3,   4],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [25]:
## Statical concept -> Normalization
## to have a mean of 0 and standard deviation of 1

data = np.array([1,2,3,4,5])

mean = np.mean(data)
std_dev = np.std(data)

normalized_data = (data - mean)/ std_dev
normalized_data

array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])

In [26]:
## Logical operations

data = np.array([1,2,3,4,5,6,7,8,9,10])

data>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [29]:
data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])